# Generated by Django 5.0.4 on 2026-04-20 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('starter', 'Luntian Starter'), ('grower', 'Luntian Grower'), ('finisher', 'Luntian Finisher'), ('lactation', 'Sow Lactation Mix')], max_length=30)),
                ('stock_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('daily_usage_kg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_restocked', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_inventory', to='piggery.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FeedUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('logged_at', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_logs', to='piggery.farm')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='piggery.feedinventory')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('antiparasitic', 'Antiparasitic'), ('vitamin', 'Vitamin'), ('vaccine', 'Vaccine'), ('other', 'Other')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(default='doses', max_length=50)),
                ('low_stock_threshold', models.PositiveIntegerField(default=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_inventory', to='piggery.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('health', 'Health Alert'), ('breeding', 'Breeding'), ('inventory', 'Inventory'), ('weather', 'Weather'), ('vaccination', 'Vaccination Due')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='piggery.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pig_id', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('breed', models.CharField(default='Landrace', max_length=100)),
                ('growth_stage', models.CharField(choices=[('piglet', 'Piglet'), ('weaner', 'Weaner'), ('grower', 'Grower'), ('finisher', 'Finisher'), ('breeder', 'Breeder')], default='piglet', max_length=20)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('under_treatment', 'Under Treatment'), ('critical', 'Critical'), ('deceased', 'Deceased')], default='healthy', max_length=20)),
                ('last_checkup_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pigs', to='piggery.farm')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('diagnosed_date', models.DateField()),
                ('treatment', models.CharField(blank=True, max_length=300)),
                ('outcome', models.CharField(choices=[('ongoing', 'Ongoing'), ('recovered', 'Recovered'), ('deceased', 'Deceased')], default='ongoing', max_length=20)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='piggery.pig')),
            ],
        ),
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_date', models.DateField()),
                ('expected_farrowing_date', models.DateField(blank=True, null=True)),
                ('actual_farrowing_date', models.DateField(blank=True, null=True)),
                ('pregnancy_status', models.CharField(choices=[('bred', 'Bred'), ('pregnant', 'Pregnant'), ('farrowed', 'Farrowed'), ('open', 'Open'), ('failed', 'Failed')], default='bred', max_length=20)),
                ('piglets_born_alive', models.PositiveIntegerField(blank=True, null=True)),
                ('piglets_born_dead', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('boar', models.ForeignKey(blank=True, limit_choices_to={'gender': 'male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sired_records', to='piggery.pig')),
                ('sow', models.ForeignKey(limit_choices_to={'gender': 'female'}, on_delete=django.db.models.deletion.CASCADE, related_name='breeding_records', to='piggery.pig')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('date_given', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('administered_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='piggery.pig')),
            ],
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recorded_at', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='piggery.pig')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
