# Generated by Django 5.0.4 on 2026-05-22 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggery', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateField(auto_now_add=True)),
                ('time_logged', models.TimeField(auto_now_add=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='Breaths per minute', null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='BPM', null=True)),
                ('appetite', models.CharField(choices=[('normal', 'Normal'), ('poor', 'Poor'), ('none', 'Not eating')], default='normal', max_length=20)),
                ('behavior', models.CharField(choices=[('normal', 'Normal'), ('lethargic', 'Lethargic'), ('aggressive', 'Aggressive'), ('isolating', 'Isolating from group')], default='normal', max_length=20)),
                ('stool_condition', models.CharField(choices=[('normal', 'Normal'), ('diarrhea', 'Diarrhea'), ('constipated', 'Constipated'), ('bloody', 'Bloody')], default='normal', max_length=20)),
                ('has_cough', models.BooleanField(default=False)),
                ('has_nasal_discharge', models.BooleanField(default=False)),
                ('has_skin_lesions', models.BooleanField(default=False)),
                ('has_lameness', models.BooleanField(default=False)),
                ('has_vomiting', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('system_findings', models.TextField(blank=True, help_text='Auto-generated by rule engine')),
                ('notes', models.TextField(blank=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='piggery.pig')),
            ],
            options={
                'ordering': ['-date_logged', '-time_logged'],
            },
        ),
    ]
