# Generated by Django 5.0.4 on 2026-05-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggery', '0003_healthlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='farm_type',
            field=models.CharField(choices=[('solo', 'Solo Farm'), ('grouped', 'Grouped/Company Farm')], default='solo', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('worker', 'Worker')], default='owner', max_length=20),
        ),
    ]
