# Generated by Django 5.0.4 on 2026-05-31 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggery', '0007_architecture_improvements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedusagelog',
            options={'ordering': ['-date_used']},
        ),
        migrations.RemoveField(
            model_name='feedusagelog',
            name='logged_at',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Login'), ('logout', 'Logout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmbaseline',
            name='common_diseases',
            field=models.TextField(blank=True, help_text='Comma-separated list of historically common diseases'),
        ),
        migrations.AlterField(
            model_name='farmbaseline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedinventory',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost per kg for feed cost analytics', max_digits=8),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='system_findings',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicineusagelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pig',
            name='is_historical',
            field=models.BooleanField(default=False, help_text='True for pigs that existed before Piglytics registration'),
        ),
        migrations.AlterField(
            model_name='pigbaseline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='farm_type',
            field=models.CharField(choices=[('solo', 'Solo Farm'), ('grouped', 'Group Farm')], default='solo', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('admin', 'Administrator')], default='farmer', max_length=20),
        ),
    ]
